### ISSUE TITLE
Opa cara! Que bom que está começando essa jornada

### ISSUE THREAD

**Issue by Camilotk** [Paulo-JRaitz/.NET-POO#1]
Aqui é o Camilo, fomos colegas no Hackaton da IBM Behind the Code, conversamos de madrugada durante uma das provas e tinha te recomendado esse caminho com os cursos da Alura, que bom que está dando sequência nessa ideia.

**Comment by Paulo-JRaitz** [comment]
Muito obrigado irmão, foi um longo caminho desde a Maratona Behind the Code. Agradeço muito pelas dicas.
